### ISSUE TITLE
ODM Issue with images not being found despite them being uploaded

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#47]
Hi, I hit a new failure case with processing multispectral image. ODM fails saying it can't find specific files which it previously had matched in earlier processing steps. 

Test I've run:
1) Uploaded and run this dataset twice (1300 images) and got the same error both times, so I think that means it isn't an issue on our end with storage or implementation, etc.
2)Tried a subset of the data that included the failed images and it also failed
3) Tried a different subset of the data w/o the failed images and that did run, so it seems to be an image file.

I was going to post this to the ODM forums, but I'm thinking it might actually be an issue related to image being cached during file upload. I can open the images ODM says aren't available on desktop, so I don't think they are faulty images. But the original task was one that I navigated away from and then had to restart and I think this happened a couple of times, so it seems possible that this is related to all that and so probably worth investigating so we can make sure that cached images are either fully uploaded or deleted.

Is there a way to flush the cache of all these specific images so I can try re-uploading them de-novo? I'm fine to delete the Tasks if needed.

Thanks

Full log file [here](https://docs.google.com/document/d/1m4g5-dmphTBMmHRb0VMABpvLYtw_-hhQWlAL6r73ZVY/edit?usp=share_link)

```
_Error: _
*[INFO]    running "/code/SuperBuild/install/bin/opensfm/bin/opensfm" export_visualsfm --points "/var/www/scratch/nodeodm-a100/nodeodm-a100-0/db3d58db-10df-4c41-96aa-c0d812a98aae/opensfm"*
*[INFO]    Multiple bands found*
*[WARNING] Cannot find 00004-DJI_0041(2)-Blue.TIF23d9bea9196301cf4741c6bda1654056.tif in image map for /var/www/scratch/nodeodm-a100/nodeodm-a100-0/db3d58db-10df-4c41-96aa-c0d812a98aae/opensfm/undistorted/reconstruction_blue.nvm*
*[WARNING] Cannot find 00006-DJI_0061(2)-Blue.TIF4ae87ca4998adee154402fb34119858e.tif in image map for /var/www/scratch/nodeodm-a100/nodeodm-a100-0/db3d58db-10df-4c41-96aa-c0d812a98aae/opensfm/undistorted/reconstruction_blue.nvm*
*[WARNING] Cannot find 00005-DJI_0051(2)-Blue.TIFe37825eecc833541293d9512aa2cd95e.tif in image map for /var/www/scratch/nodeodm-a100/nodeodm-a100-0/db3d58db-10df-4c41-96aa-c0d812a98aae/opensfm/undistorted/reconstruction_blue.nvm*
*[WARNING] Cannot find 00001-DJI_0011(2)-Blue.TIF3947856d330d174919aaba8afec177c3.tif in image map for /var/www/scratch/nodeodm-a100/nodeodm-a100-0/db3d58db-10df-4c41-96aa-c0d812a98aae/opensfm/undistorted/reconstruction_blue.nvm*
*[WARNING] Cannot find 00007-DJI_0071(2)-Blue.TIFbd7805307b50b084950ed1d50b3d13d7.tif in image map for /var/www/scratch/nodeodm-a100/nodeodm-a100-0/db3d58db-10df-4c41-96aa-c0d812a98aae/opensfm/undistorted/reconstruction_blue.nvm*
*[WARNING] Cannot find 00003-DJI_0031(2)-Blue.TIFc10e319a8bfea8063a1ed03ef2f326d5.tif in image map for /var/www/scratch/nodeodm-a100/nodeodm-a100-0/db3d58db-10df-4c41-96aa-c0d812a98aae/opensfm/undistorted/reconstruction_blue.nvm*
*[WARNING] Cannot find 00002-DJI_0021(2)-Blue.TIFad5d8a1d2fedf6c5f99e52b5f41f89cf.tif in image map for /var/www/scratch/nodeodm-a100/nodeodm-a100-0/db3d58db-10df-4c41-96aa-c0d812a98aae/opensfm/undistorted/reconstruction_blue.nvm*
*Traceback (most recent call last):*
*File "/code/run.py", line 59, in <module>*
*retcode = app.execute()*
*File "/code/stages/odm_app.py", line 117, in execute*
*raise e*
*File "/code/stages/odm_app.py", line 81, in execute*
*self.first_stage.run()*
*File "/code/opendm/types.py", line 397, in run*
*self.next_stage.run(outputs)*
*File "/code/opendm/types.py", line 397, in run*
*self.next_stage.run(outputs)*
*File "/code/opendm/types.py", line 397, in run*
*self.next_stage.run(outputs)*
*File "/code/opendm/types.py", line 376, in run*
*self.process(self.args, outputs)*
*File "/code/stages/run_opensfm.py", line 226, in process*
*nvm.replace_nvm_images(tree.opensfm_reconstruction_nvm, img_map, nvm_file)*
*File "/code/opendm/nvm.py", line 35, in replace_nvm_images*
*raise Exception("Cannot write %s, not all band images have been matched" % dst_nvm_file)*
*Exception: Cannot write /var/www/scratch/nodeodm-a100/nodeodm-a100-0/db3d58db-10df-4c41-96aa-c0d812a98aae/opensfm/undistorted/reconstruction_blue.nvm, not all band images have been matched*

**Comment by TimeScience** [comment]
Issue was caused by a known ODM error (spaces in filenames cause ODM to fail).
